version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - yum install zip -y || (apt update && apt install zip -y)
      - yum install jq -y

  pre_build:
    commands:

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      # - python -m unittest discover tests
      - if [ $loglevel == 'DEBUG' ];then cat src/chef/chef_client_component.yaml; fi
      - aws cloudformation validate-template --template-body "$(cat src/chef/chef_client_component.yaml)"
  
  build:
    commands:
      
      # Code bucket from code_bucket_stack
      # - S3_STACK_NAME="codedeploy-${AWS_REGION}-image-builder-code"
      # - S3_BUCKET="${S3_STACK_NAME}-$(aws sts get-caller-identity --query 'Account' --output text)"
      
      # Build Component Lambda Function artifacts from requirements and code
      - if [ $loglevel == 'DEBUG' ];then pwd; ls; fi
      - python3 -m venv v-env
      - source v-env/bin/activate && pip install -qq -r src/chef/lambda/requirements.txt && deactivate
      - cd src/chef/lambda
      - zip -q -r9 ${CODEBUILD_SRC_DIR}/src/chef/component_lambda_code.zip .
      - cd $CODEBUILD_SRC_DIR
      - if [ $loglevel == 'DEBUG' ];then pwd; ls; fi
      - cd v-env/lib/python3.8/site-packages
      - zip -q -r9 ${CODEBUILD_SRC_DIR}/src/chef/component_lambda_code.zip .

      # Package the application by using AWS CloudFormation
      - cd $CODEBUILD_SRC_DIR
      - if [ $loglevel == 'DEBUG' ];then pwd; ls; fi
      - S3_PREFIX="image_builder_components"
      - cp -f $CODEBUILD_SRC_DIR_DeployCodeBucketOutput/code-bucket-exports.json .
      - CODE_BUCKET=$(cat code-bucket-exports.json|jq '.CodeBucketName'|sed 's/"//g')
      - if [ $loglevel == 'DEBUG' ];then echo $(echo $CODE_BUCKET; echo $S3_PREFIX); fi
      - if [ $loglevel == 'DEBUG' ];then pwd; ls; fi
      - aws cloudformation package --template src/chef/chef_client_component.yaml --s3-bucket $CODE_BUCKET --s3-prefix $S3_PREFIX --force-upload --output-template chef-template-export.yml
      - if [ $loglevel == 'DEBUG' ];then cat chef-template-export.yml; fi

artifacts:
  files:
    - chef-template-export.yml
