version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chef-component"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mwguteefhtfy"
s3_prefix = "chef-component"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

