AWSTemplateFormatVersion: 2010-09-09
Description: iam-roles-policies-for-image-builder
Conditions:
  GovCloudCondition: !Equals 
    - !Ref 'AWS::Region'
    - us-gov-west-1
Resources:
  ManageComponentsLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref IAMPolicyToManageImageBuilderComponents
        - !Sub 
          - >-
            arn:${Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - Partition: !If 
              - GovCloudCondition
              - aws-us-gov
              - aws
  IAMPolicyToManageImageBuilderComponents:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: ManageImageBuilderComponents
      Path: /service-role/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ImageBuilderComponentManagement
            Effect: Allow
            Action:
              - 'imagebuilder:ListComponents'
              - 'imagebuilder:CreateComponent'
              - 'imagebuilder:DeleteComponent'
              - 'imagebuilder:TagResource'
            Resource: '*'
          - Sid: ImageBuilderServiceLinkedRole
            Effect: Allow
            Action:
              - 'iam:CreateServiceLinkedRole'
            Resource: arn:aws:iam::*:role/aws-service-role/imagebuilder.amazonaws.com/AWSServiceRoleForImageBuilder
            Condition:
              ForAllValues:StringEquals:
                iam:AWSServiceName: imagebuilder.amazonaws.com
Outputs:
  ManageComponentsLambdaRoleArn:
    Description: Lambda Role for Image Builder Component management
    Value: !GetAtt
      - ManageComponentsLambdaRole
      - Arn
    Export:
      Name: ManageComponentsLambdaRoleArn
